/**
 * @arkmp/emitter —— L3 产物拼装（docs/arkui-miniprogram/02-pipeline.md ⑤ emit）。
 *
 * 把 L2 四条转换链的产物片段拼装为小程序四件套 `{ path, content }[]`：
 *
 * | 产物 | 处理 |
 * | --- | --- |
 * | `<base>.wxml` | 头部加 `<!-- Generated by ArkMP, do not edit -->`（幂等） |
 * | `<base>.wxss` | 前置 runtime `BASE_WXSS` 基础类，再按「选择器 + 声明体」去重 |
 * | `<base>.js` | 头部加 `// Generated by ArkMP, do not edit`（幂等；transform-js 已带则不重复） |
 * | `<base>.json` | 2 空格缩进序列化 |
 *
 * 统一约定：产物恰好以一个 `\n` 结尾；缩进由上游各 transform 产出，
 * emitter 不重排缩进（重排有破坏 `{{}}` 内文本的风险）。
 *
 * `<base>` 由 `options.fileName` 去掉 `.ets` 后缀得到（缺省 `index.ets` → `index`），
 * 目录部分保留（`pages/Index.ets` → `pages/Index.wxml` 等）。
 *
 * ## sourcemap（`options.sourcemap: true`）
 *
 * 额外产出 `<base>.js.map`（v3），并在 js 末尾追加 `//# sourceMappingURL`。
 * `sources` 指回 `.ets` 文件名，`sourcesContent` 内嵌原始源码。
 *
 * **粒度限制**：js 产物中的方法体是从 `.ets` 源码抽取（并可能经赋值改写）
 * 的文本，本包按「生成行文本 ↔ 源码行文本」匹配建立行级映射——方法体内
 * 未被改写的行可回溯到源码行列；结构行（`createPage({...})` 包装、`state`
 * 初始值表、头注释等）与经 `__set` 改写的行无映射；重复文本行取源码中
 * 首个未被消费的匹配，可能与实际出处不符。
 */

import { BASE_WXSS } from '@arkmp/runtime';

/** 一个产物文件（相对路径 + 文本内容）。 */
export interface EmittedFile {
  path: string;
  content: string;
}

/** 四条转换链的产物片段（emitter 的输入）。 */
export interface EmitInput {
  /** transform-wxml 产物（应已合并 classMap/inlineStyles） */
  wxml: string;
  /** transform-wxss 产物（页面类，不含 runtime 基础类） */
  wxss: string;
  /** transform-js 产物 */
  js: string;
  /** transform-json 产物（未序列化的配置对象） */
  json: Record<string, unknown>;
}

export interface EmitOptions {
  /** 源文件名，如 `index.ets`；产物路径由其派生，缺省 `index.ets` */
  fileName?: string;
  /** 生成 js sourcemap（v3）；需要同时提供 `source` 才有 sourcesContent 与行映射 */
  sourcemap?: boolean;
  /** 原始 `.ets` 源码，用于 sourcemap 的 sourcesContent 与行映射 */
  source?: string;
}

const JS_HEADER = '// Generated by ArkMP, do not edit';
const WXML_HEADER = '<!-- Generated by ArkMP, do not edit -->';

/**
 * 拼装四件套（02 篇⑤）。纯函数，无文件 I/O。
 * `sourcemap: true` 时追加 `<base>.js.map` 产物。
 */
export function emit(input: EmitInput, options: EmitOptions = {}): EmittedFile[] {
  const fileName = options.fileName ?? 'index.ets';
  const base = fileName.replace(/\.ets$/u, '');

  const wxml = ensureHeader(input.wxml, WXML_HEADER);
  const wxss = mergeWxss(input.wxss);

  let js = ensureHeader(input.js, JS_HEADER);
  const files: EmittedFile[] = [
    { path: `${base}.wxml`, content: singleTrailingNewline(wxml) },
    { path: `${base}.wxss`, content: singleTrailingNewline(wxss) },
  ];

  if (options.sourcemap === true) {
    const mapPath = `${base}.js.map`;
    const map = generateSourceMap(js, {
      file: `${baseName(base)}.js`,
      sourceName: fileName,
      source: options.source,
    });
    js = `${js}\n//# sourceMappingURL=${baseName(mapPath)}`;
    files.push({ path: `${base}.js`, content: singleTrailingNewline(js) });
    files.push({ path: mapPath, content: JSON.stringify(map, null, 2) + '\n' });
  } else {
    files.push({ path: `${base}.js`, content: singleTrailingNewline(js) });
  }

  files.push({ path: `${base}.json`, content: JSON.stringify(input.json, null, 2) + '\n' });
  return files;
}

// ── 头注释与尾部换行 ──

/** 头部注释（幂等：已存在则不重复添加）。 */
function ensureHeader(content: string, header: string): string {
  return content.startsWith(header) ? content : `${header}\n${content}`;
}

/** 恰好一个尾部换行。 */
function singleTrailingNewline(content: string): string {
  return `${content.replace(/\n+$/u, '')}\n`;
}

/** 取路径的最后一段（`pages/index` → `index`）。 */
function baseName(path: string): string {
  const slash = path.lastIndexOf('/');
  return slash === -1 ? path : path.slice(slash + 1);
}

// ── WXSS：前置 BASE_WXSS + 规则去重 ──

interface CssRule {
  /** 去重键：选择器 + 规范化声明体 */
  key: string;
  /** 原始规则文本（保留上游排版） */
  text: string;
}

/** 解析 CSS 规则块（`selector { body }`，不支持嵌套语法——产物中也不会出现）。 */
function parseRules(css: string): CssRule[] {
  const rules: CssRule[] = [];
  const pattern = /([^{}]+)\{([^{}]*)\}/gu;
  let match = pattern.exec(css);
  while (match !== null) {
    const selector = match[1].trim();
    const body = match[2]
      .split(';')
      .map((decl) => decl.trim())
      .filter((decl) => decl !== '')
      .join(';');
    if (selector !== '') {
      rules.push({ key: `${selector}{${body}}`, text: match[0].trim() });
    }
    match = pattern.exec(css);
  }
  return rules;
}

/**
 * 前置 runtime 基础类（BASE_WXSS）后去重：
 * 「选择器 + 声明体」完全相同的规则只保留首次出现（04 篇：相同样式组合去重为一个类）。
 */
function mergeWxss(pageWxss: string): string {
  const base = BASE_WXSS.replace(/\n+$/u, '');
  const seen = new Set(parseRules(BASE_WXSS).map((rule) => rule.key));
  const kept: string[] = [];
  for (const rule of parseRules(pageWxss)) {
    if (seen.has(rule.key)) continue;
    seen.add(rule.key);
    kept.push(rule.text);
  }
  return kept.length === 0 ? base : `${base}\n\n${kept.join('\n\n')}`;
}

// ── sourcemap（v3，手写 base64 VLQ，零依赖） ──

interface SourceMapOptions {
  /** map 的 `file` 字段（产物 js 文件名） */
  file: string;
  /** `sources` 中的源文件名（`.ets`） */
  sourceName: string;
  /** 原始源码；缺省时 mappings 为空（map 仍合法） */
  source?: string;
}

interface SourceMapV3 {
  version: 3;
  file: string;
  sources: string[];
  sourcesContent: Array<string | null>;
  names: string[];
  mappings: string;
}

/**
 * 生成 v3 sourcemap。行映射策略见文件头「粒度限制」：
 * 生成行去空白后的文本在源码中按序消费首个匹配行，命中则建立
 * `[生成列, 0, 源码行, 源码列]` 单段映射（列取双方首个非空白字符处）。
 */
function generateSourceMap(js: string, options: SourceMapOptions): SourceMapV3 {
  return {
    version: 3,
    file: options.file,
    sources: [options.sourceName],
    sourcesContent: [options.source ?? null],
    names: [],
    mappings: options.source === undefined ? '' : buildMappings(js, options.source),
  };
}

/** 生成行 ↔ 源码行的内容匹配映射（mappings 字段，';' 分行）。 */
function buildMappings(js: string, source: string): string {
  // 源码行（去空白文本）→ 未消费的 0 起始行号队列
  const sourceArr = source.split('\n');
  const sourceLines = new Map<string, number[]>();
  sourceArr.forEach((text, index) => {
    const key = text.trim();
    if (key === '') return;
    const queue = sourceLines.get(key);
    if (queue === undefined) sourceLines.set(key, [index]);
    else queue.push(index);
  });

  const lines: string[] = [];
  let previousSourceLine = 0;
  let previousSourceColumn = 0;
  for (const generatedLine of js.split('\n')) {
    const key = generatedLine.trim();
    const queue = key === '' ? undefined : sourceLines.get(key);
    const sourceLine = queue !== undefined && queue.length > 0 ? queue.shift() : undefined;
    if (sourceLine === undefined) {
      lines.push('');
      continue;
    }
    const generatedColumn = generatedLine.length - generatedLine.trimStart().length;
    const sourceColumn = leadingWhitespace(sourceArr[sourceLine]);
    lines.push(
      vlq(generatedColumn) +
        vlq(0) + // sources 下标恒为 0（相对上一段无变化）
        vlq(sourceLine - previousSourceLine) +
        vlq(sourceColumn - previousSourceColumn),
    );
    previousSourceLine = sourceLine;
    previousSourceColumn = sourceColumn;
  }
  return lines.join(';');
}

function leadingWhitespace(line: string | undefined): number {
  if (line === undefined) return 0;
  return line.length - line.trimStart().length;
}

const BASE64_CHARS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';

/** base64 VLQ 编码单个有符号整数（sourcemap v3 规范）。 */
function vlq(value: number): string {
  let shifted = value < 0 ? (-value << 1) | 1 : value << 1;
  let out = '';
  do {
    let digit = shifted & 31;
    shifted >>>= 5;
    if (shifted > 0) digit |= 32;
    out += BASE64_CHARS[digit];
  } while (shifted > 0);
  return out;
}
