/**
 * app 级产物（app.js / app.json / app.wxss / project.config.json）的生成。
 *
 * app.ets 无 build()，不经过 @arkmp/pipeline（analyzer 对缺 build() 的组件报
 * E1xxx 错误），这里做最小特判：生成 `App({})` 形态入口，忽略 app.ets 内容；
 * app.json 由 options（window/tabBar/permission）+ 扫描到的 @Entry 页面列表合成。
 */

import { warningDiagnostic } from '@arkmp/diagnostics';
import type { Diagnostic } from '@arkmp/diagnostics';
import { outputBaseFor } from './paths';

/** compiler 包诊断码。 */
export const COMPILER_DIAGNOSTIC_CODES = {
  /** tabBar.pages 引用的页面名未匹配到任何 @Entry 页面 */
  TABBAR_PAGE_NOT_FOUND: 'W6001',
  /** 自定义组件未找到提供方文件 */
  COMPONENT_PROVIDER_NOT_FOUND: 'W6002',
  /** @arkmp/runtime 单文件产物缺失（需先构建 runtime 包） */
  RUNTIME_NOT_FOUND: 'E6001',
  /** src/ 下不属于 app/pages/components 的 .ets，已跳过 */
  SKIPPED_SOURCE: 'W6003',
} as const;

/** arkmp.config.ts 对齐的 tabBar 配置（07 篇）：pages 按页面名引用。 */
export interface TabBarOptions {
  pages: Array<{ name: string; text: string; icon?: string }>;
  [key: string]: unknown;
}

const HEADER_JS = '// Generated by ArkMP, do not edit\n';
const HEADER_WXSS = '/* Generated by ArkMP, do not edit */\n';

/** app.js：最小 App() 形态（app.ets 内容当前不解析，见 08 篇限制）。 */
export function buildAppJs(): string {
  return `${HEADER_JS}App({});\n`;
}

/** app.wxss：仅占位（基础类由 emitter 注入各页面 wxss）。 */
export function buildAppWxss(): string {
  return HEADER_WXSS;
}

export interface AppJsonInput {
  /** @Entry 页面路由（`pages/index/index`），排序后第一个为首页 */
  pageRoutes: string[];
  /** struct 名 → 路由，用于 tabBar.pages[].name 解析 */
  routeByName: ReadonlyMap<string, string>;
  window?: Record<string, unknown>;
  tabBar?: TabBarOptions;
  permission?: Record<string, unknown>;
}

/** app.json：pages 列表 + window/tabBar/permission 合并。 */
export function buildAppJson(input: AppJsonInput): { json: Record<string, unknown>; diagnostics: Diagnostic[] } {
  const diagnostics: Diagnostic[] = [];
  const json: Record<string, unknown> = { pages: input.pageRoutes };

  if (input.window !== undefined) {
    json.window = { ...input.window };
  }
  if (input.tabBar !== undefined) {
    const { pages, ...rest } = input.tabBar;
    const list = pages.map((page) => {
      const route = input.routeByName.get(page.name);
      if (route === undefined) {
        diagnostics.push(
          warningDiagnostic(
            COMPILER_DIAGNOSTIC_CODES.TABBAR_PAGE_NOT_FOUND,
            `tabBar.pages 引用的页面 "${page.name}" 未匹配到任何 @Entry 页面，已跳过`,
          ),
        );
        return undefined;
      }
      return {
        pagePath: route,
        text: page.text,
        ...(page.icon !== undefined ? { iconPath: page.icon } : {}),
      };
    });
    json.tabBar = { ...rest, list: list.filter((item) => item !== undefined) };
  }
  if (input.permission !== undefined) {
    json.permission = { ...input.permission };
  }
  return { json, diagnostics };
}

/** project.config.json（appId 存在时生成，微信开发者工具直接打开 dist/）。 */
export function buildProjectConfig(appId: string, appName?: string): Record<string, unknown> {
  return {
    appid: appId,
    projectname: appName ?? 'arkmp-app',
    compileType: 'miniprogram',
  };
}

/** 页面/组件 json 中合并 usingComponents（覆盖式序列化，保持 2 空格缩进约定）。 */
export function mergeUsingComponents(
  jsonContent: string,
  usingComponents: Record<string, string>,
): string {
  const json = JSON.parse(jsonContent) as Record<string, unknown>;
  json.usingComponents = usingComponents;
  return `${JSON.stringify(json, null, 2)}\n`;
}

/** 页面路由（app.json pages 项）：源文件 → 产物基路径。 */
export function routeFor(srcRelativePath: string): string {
  return outputBaseFor(srcRelativePath);
}
