/**
 * @arkmp/transform-js —— L2 JS 转换链（02 篇④「states/props → JS 生成器」，
 * 05 篇装饰器转换规则）。
 *
 * 输入 ComponentModel（IR），输出页面/组件 `.js` 产物文本：
 *
 * ```js
 * // Generated by ArkMP, do not edit
 * const { createPage } = require('@arkmp/runtime');
 *
 * createPage({
 *   state: { count: 0 },
 *   watch: { count: 'onCountChange' },
 *   methods: {
 *     aboutToAppear(options) { ... },
 *     __n7_click() { this.__set('count', this.count + 1); },
 *   },
 * });
 * ```
 *
 * ## 与 @arkmp/runtime 的衔接协议
 *
 * - 页面调 `createPage`，组件调 `createComponent`（06 篇/runtime L5）；
 * - `@State` → `state` 初始值表；runtime 在 onLoad/attached 安装访问器 +
 *   批量 setData 调度 + `this.__set(path, value)` 桥接入口；
 * - `@Prop` / `@Link` → `properties`（小程序原生属性表）；
 * - 无装饰器普通成员 → `data`（独立段，非响应式初始值；runtime 透传给小程序
 *   data 供 WXML `{{}}` 绑定读取，但不安装访问器，赋值不触发刷新）；
 * - `@Link` 另生成 `__set_<name>(v)` 桥接方法（setData +
 *   `triggerEvent('update:<name 全小写>', v)`），编译期把 `this.<name> = v`
 *   改写为 `__set_<name>(v)` 调用，实现 05 篇双向绑定协议；
 * - `@Watch` → `watch: { <字段>: '<回调方法名>' }`，runtime 在编译期改写
 *   （__set）与 Proxy 兜底两条路径下都会同步触发回调（05 篇「@Watch」）；
 * - 生命周期：钩子体以 **ArkUI 名称**放入 `methods`（页面：aboutToAppear /
 *   onPageShow / onDidBuild / onPageHide / aboutToDisappear / onPullRefresh；
 *   组件：aboutToAppear / onDidBuild / aboutToDisappear），ArkUI → 小程序钩子
 *   （onLoad/attached 等，05 篇映射表）的分发由 runtime 的
 *   createPage/createComponent 完成——组件侧必须如此，因为小程序
 *   Component 的生命周期在 `lifetimes` 块而非 `methods` 中；
 *   小程序原生命名钩子（onLoad/onShow/attached 等）经 analyzer 归入
 *   model.methods 原样输出，由 runtime 恒等映射或透传，从而同时支持两套命名；
 * - 页面 `aboutToAppear` 声明 `options` 形参（runtime 注入路由参数，05 篇）。
 *
 * ## 与 transform-events 的方法合并协议
 *
 * transform-events 只抽取事件回调体（`__n7_click` 式方法名 → 源码文本），
 * 不做赋值改写。调用方把其结果作为 `options.eventMethods` 传入本包，
 * 本包对声明方法与事件方法应用同一套赋值改写（rewrite.ts）后合并进
 * `methods`，事件方法排在声明方法之后。
 *
 * 诊断码：W2001（动态键等无法静态改写，08 篇）、W2002（@State 初始值
 * 不是编译期静态表达式，降级为 null）。
 */

import type { Diagnostic } from '@arkmp/diagnostics';
import { warningDiagnostic } from '@arkmp/diagnostics';
import type { ComponentModel, Expression, PropField, StateField } from '@arkmp/ir';
import { rewriteBody } from './rewrite';

export { rewriteBody, REWRITE_WARNING_CODES } from './rewrite';
export type { RewriteResult, RewriteTargets, RewriteWarning } from './rewrite';

/** transform-js 诊断码（改写器自身的码见 rewrite.ts）。 */
export const TRANSFORM_JS_WARNING_CODES = {
  /** @State/@Prop 初始值不是编译期静态表达式 */
  NON_STATIC_INITIAL_VALUE: 'W2002',
} as const;

export interface EventMethod {
  body: string;
  /** ForEach 循环变量名（外层到内层），回调体中需改写为 e.currentTarget.dataset.<name> */
  loopVars?: string[];
}

export interface TransformJsOptions {
  /** 强制按页面/组件产物生成；缺省取 `model.isEntry` */
  isPage?: boolean;
  /** transform-events 抽取的事件方法（方法名 → EventMethod），见头部合并协议 */
  eventMethods?: Record<string, EventMethod>;
}

export interface TransformJsResult {
  js: string;
  diagnostics: Diagnostic[];
}

const HEADER = '// Generated by ArkMP, do not edit';

/** 页面生命周期钩子的固定输出顺序（05 篇映射表顺序）。 */
const PAGE_LIFECYCLE_ORDER = [
  'aboutToAppear',
  'onPageShow',
  'onDidBuild',
  'onPageHide',
  'aboutToDisappear',
  'onPullRefresh',
] as const;
/** 组件生命周期钩子的固定输出顺序。 */
const COMPONENT_LIFECYCLE_ORDER = ['aboutToAppear', 'onDidBuild', 'aboutToDisappear'] as const;

/** 序列化初始值字面量；非静态表达式返回 null 并告警。 */
function initialValueLiteral(
  field: string,
  initialValue: Expression | undefined,
  diagnostics: Diagnostic[],
): string {
  if (initialValue === undefined) return 'null';
  if (initialValue.kind === 'static') {
    const text = JSON.stringify(initialValue.value);
    return text === undefined ? 'null' : text;
  }
  diagnostics.push(
    warningDiagnostic(
      TRANSFORM_JS_WARNING_CODES.NON_STATIC_INITIAL_VALUE,
      `字段 "${field}" 的初始值依赖状态绑定，无法作为静态初始值，已降级为 null`,
      { help: '初始值须为编译期可序列化的字面量表达式（05 篇「@State → data」）' },
    ),
  );
  return 'null';
}

/** 属性类型文本 → 小程序 properties 类型构造器。 */
function propertyTypeCtor(type: string): string {
  const t = type.trim();
  if (t === 'number') return 'Number';
  if (t === 'string') return 'String';
  if (t === 'boolean') return 'Boolean';
  if (t.endsWith('[]') || /^Array</.test(t)) return 'Array';
  return 'Object';
}

/** properties 表项：有静态初始值用完整形式，否则用简写形式（05 篇「@Prop」）。 */
function propertyEntry(prop: PropField, diagnostics: Diagnostic[]): string {
  const ctor = propertyTypeCtor(prop.type);
  if (prop.initialValue === undefined) return ctor;
  const value = initialValueLiteral(prop.name, prop.initialValue, diagnostics);
  return `{ type: ${ctor}, value: ${value} }`;
}

/** 去掉公共缩进后按指定缩进重排方法体。 */
function indentBody(body: string, indent: string): string {
  const lines = body.replace(/\s+$/u, '').split('\n');
  const nonEmpty = lines.filter((line) => line.trim() !== '');
  const minIndent = nonEmpty.reduce<number>((min, line) => {
    const match = /^[ \t]*/u.exec(line);
    return Math.min(min, match === null ? 0 : match[0].length);
  }, Number.POSITIVE_INFINITY);
  const strip = Number.isFinite(minIndent) ? minIndent : 0;
  return lines.map((line) => (line.trim() === '' ? '' : indent + line.slice(strip))).join('\n');
}

interface EmittedMethod {
  name: string;
  params: string[];
  body: string;
}

/**
 * JS 转换（02 篇④⑤）：ComponentModel → `createPage`/`createComponent` 调用文本。
 * 纯函数；产物形态见文件头示例与 docs/arkui-miniprogram/README.md 末尾示例。
 */
export function transformJs(model: ComponentModel, options: TransformJsOptions = {}): TransformJsResult {
  const isPage = options.isPage ?? model.isEntry;
  const diagnostics: Diagnostic[] = [];
  const states = model.states.map((s: StateField) => s.name);
  const links = model.props.filter((p) => p.kind === 'link').map((p) => p.name);
  const rewriteTargets = { states: new Set(states), links: new Set(links) };

  const rewrite = (body: string, loopVars?: string[]): string => {
    const result = rewriteBody(body, rewriteTargets);
    for (const warning of result.warnings) {
      diagnostics.push(warningDiagnostic(warning.code, warning.message));
    }
    let code = result.code;
    // ForEach 循环变量 → e.currentTarget.dataset.<name>
    // （transform-wxml 在元素上补 data-<name>="{{<name>}}"，runtime 从 dataset 读取）
    if (loopVars !== undefined && loopVars.length > 0) {
      for (const v of loopVars) {
        code = code.replace(new RegExp(`\\b${v}\\b`, 'g'), `e.currentTarget.dataset.${v}`);
      }
    }
    return code;
  };

  // ---- methods：生命周期 → @Link 桥接 → 声明方法 → 事件方法 ----
  const methods: EmittedMethod[] = [];
  const lifecycleOrder = isPage ? PAGE_LIFECYCLE_ORDER : COMPONENT_LIFECYCLE_ORDER;
  for (const hook of lifecycleOrder) {
    const body = model.lifecycle[hook];
    if (body === undefined) continue;
    // 页面 aboutToAppear 接收路由参数（runtime 注入，05 篇映射表）
    const params = isPage && hook === 'aboutToAppear' ? ['options'] : [];
    methods.push({ name: hook, params, body: rewrite(body) });
  }
  for (const name of links) {
    methods.push({
      name: `__set_${name}`,
      params: ['v'],
      body: `this.setData({ ${name}: v });\nthis.triggerEvent('update:${name.toLowerCase()}', v);`,
    });
  }
  for (const method of model.methods) {
    methods.push({ name: method.name, params: method.params, body: rewrite(method.body) });
  }
  if (options.eventMethods !== undefined) {
    for (const [name, m] of Object.entries(options.eventMethods)) {
      // 有循环变量的事件方法（在 ForEach 内）：加 e 参数接收小程序事件对象
      const params = m.loopVars !== undefined && m.loopVars.length > 0 ? ['e'] : [];
      methods.push({ name, params, body: rewrite(m.body, m.loopVars) });
    }
  }

  // ---- 组装产物文本 ----
  const factory = isPage ? 'createPage' : 'createComponent';
  const sections: string[] = [];

  const propFields = model.props.filter((p) => p.kind !== 'plain');
  if (propFields.length > 0) {
    const entries = propFields.map((p) => `    ${p.name}: ${propertyEntry(p, diagnostics)},`);
    sections.push(`  properties: {\n${entries.join('\n')}\n  },`);
  }

  // plain 普通成员：输出到独立 data 段（非响应式，runtime 透传给小程序 data）
  const plainFields = model.props.filter((p) => p.kind === 'plain');
  if (plainFields.length > 0) {
    const entries = plainFields.map((p) => `    ${p.name}: ${initialValueLiteral(p.name, p.initialValue, diagnostics)},`);
    sections.push(`  data: {\n${entries.join('\n')}\n  },`);
  }

  if (model.states.length > 0) {
    const entries = model.states.map((s) => `    ${s.name}: ${initialValueLiteral(s.name, s.initialValue, diagnostics)},`);
    sections.push(`  state: {\n${entries.join('\n')}\n  },`);
  }

  const watched = model.states.filter((s) => s.watch !== undefined);
  if (watched.length > 0) {
    const entries = watched.map((s) => `    ${s.name}: '${s.watch}',`);
    sections.push(`  watch: {\n${entries.join('\n')}\n  },`);
  }

  if (methods.length > 0) {
    const blocks = methods.map((m) => {
      const params = m.params.join(', ');
      const body = indentBody(m.body, '      ');
      return body === '' ? `    ${m.name}(${params}) {},` : `    ${m.name}(${params}) {\n${body}\n    },`;
    });
    sections.push(`  methods: {\n${blocks.join('\n')}\n  },`);
  }

  const js = `${HEADER}\nconst { ${factory} } = require('@arkmp/runtime');\n\n${factory}({\n${sections.join('\n')}\n});\n`;
  return { js, diagnostics };
}
