import { describe, expect, it } from 'vitest';
import { BASE_WXSS } from '@arkmp/runtime';
import { emit } from '../src/index';
import type { EmittedFile } from '../src/index';

/** 构造一份典型的四链产物片段（形态与 transform-* 输出一致）。 */
function sampleInput() {
  return {
    wxml: '<view class="arkmp-col arkmp-n0" style="gap: 24rpx">\n  <text class="arkmp-n1">点击次数：{{count}}</text>\n  <view class="arkmp-btn" bindtap="__n2_click">点我 +1</view>\n</view>\n',
    wxss: '.arkmp-n0 {\n  width: 100%;\n  justify-content: center;\n}\n\n.arkmp-n1 {\n  font-size: 40rpx;\n}\n',
    js: "// Generated by ArkMP, do not edit\nconst { createPage } = require('@arkmp/runtime');\n\ncreatePage({\n  state: {\n    count: 0,\n  },\n  methods: {\n    __n2_click() {\n      this.__set('count', this.count + 1);\n    },\n  },\n});\n",
    json: { navigationBarTitleText: '首页' },
  };
}

function byPath(files: EmittedFile[]): Map<string, string> {
  return new Map(files.map((f) => [f.path, f.content]));
}

/** 简易 base64 VLQ 解码（测试用）：mappings → 每行段数组 [genCol, srcIdx, srcLine, srcCol]。 */
function decodeMappings(mappings: string): number[][][] {
  const CHARS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
  const decodeVlq = (text: string, start: number): [number, number] => {
    let result = 0;
    let shift = 0;
    let i = start;
    for (; i < text.length; i += 1) {
      const digit = CHARS.indexOf(text[i]);
      result |= (digit & 31) << shift;
      shift += 5;
      if ((digit & 32) === 0) break;
    }
    const negative = result & 1;
    return [(negative === 1 ? -(result >> 1) : result >> 1), i + 1];
  };
  // 规范：除生成列外的字段在整个 mappings 内累计（跨行），生成列每行清零
  const prev = [0, 0, 0, 0];
  return mappings.split(';').map((line) => {
    prev[0] = 0;
    const segments: number[][] = [];
    for (const seg of line.split(',')) {
      if (seg === '') continue;
      const values: number[] = [];
      let pos = 0;
      while (pos < seg.length) {
        const [value, next] = decodeVlq(seg, pos);
        values.push(value);
        pos = next;
      }
      const absolute = values.map((v, i) => v + prev[i]);
      for (let i = 0; i < absolute.length; i += 1) prev[i] = absolute[i];
      segments.push(absolute);
    }
    return segments;
  });
}

describe('四件套拼装（02 篇⑤）', () => {
  it('产出 wxml/wxss/js/json 四件套，路径由 fileName 派生', () => {
    const files = emit(sampleInput(), { fileName: 'index.ets' });
    expect(files.map((f) => f.path)).toEqual(['index.wxml', 'index.wxss', 'index.js', 'index.json']);
    for (const file of files) {
      expect(file.content.endsWith('\n')).toBe(true);
      expect(file.content.endsWith('\n\n')).toBe(false);
    }
    for (const file of files) {
      expect(`=== ${file.path} ===\n${file.content}`).toMatchSnapshot();
    }
  });

  it('默认 fileName 为 index.ets；目录部分保留', () => {
    expect(emit(sampleInput()).map((f) => f.path)).toEqual([
      'index.wxml',
      'index.wxss',
      'index.js',
      'index.json',
    ]);
    expect(emit(sampleInput(), { fileName: 'pages/Index.ets' }).map((f) => f.path)).toEqual([
      'pages/Index.wxml',
      'pages/Index.wxss',
      'pages/Index.js',
      'pages/Index.json',
    ]);
  });

  it('wxml 头部加 <!-- --> 注释，js 头部注释幂等', () => {
    const files = byPath(emit(sampleInput()));
    expect(files.get('index.wxml')).toMatch(/^<!-- Generated by ArkMP, do not edit -->\n/);
    // transform-js 产物已带头注释，不应重复
    const js = files.get('index.js') ?? '';
    expect(js.match(/Generated by ArkMP/g)).toHaveLength(1);
  });

  it('js 缺少头注释时补齐', () => {
    const input = { ...sampleInput(), js: 'createPage({});\n' };
    const js = byPath(emit(input)).get('index.js') ?? '';
    expect(js).toMatch(/^\/\/ Generated by ArkMP, do not edit\n/);
  });

  it('wxss 前置 BASE_WXSS 基础类', () => {
    const wxss = byPath(emit(sampleInput())).get('index.wxss') ?? '';
    expect(wxss.startsWith(BASE_WXSS.replace(/\n+$/u, ''))).toBe(true);
    expect(wxss).toContain('.arkmp-col{display:flex;flex-direction:column;}');
    expect(wxss).toContain('.arkmp-n0 {');
  });

  it('wxss 去重：与基础类完全相同的规则只保留一次', () => {
    const input = {
      ...sampleInput(),
      wxss: '.arkmp-col {\n  display: flex;\n  flex-direction: column;\n}\n\n.arkmp-n1 {\n  font-size: 40rpx;\n}\n',
    };
    const wxss = byPath(emit(input)).get('index.wxss') ?? '';
    // 页面类 `.arkmp-col{display:flex;flex-direction:column}` 与 BASE_WXSS 重复，应被去重
    expect(wxss.match(/\.arkmp-col\{/g)).toHaveLength(1);
    expect(wxss).toContain('.arkmp-n1 {');
  });

  it('wxss 为空时只输出 BASE_WXSS', () => {
    const wxss = byPath(emit({ ...sampleInput(), wxss: '' })).get('index.wxss') ?? '';
    expect(wxss).toBe(BASE_WXSS.replace(/\n+$/u, '') + '\n');
  });

  it('json 以 2 空格缩进序列化', () => {
    const json = byPath(emit(sampleInput())).get('index.json') ?? '';
    expect(json).toBe('{\n  "navigationBarTitleText": "首页"\n}\n');
  });
});

describe('sourcemap（T30）', () => {
  const source = [
    '@Entry',
    '@Component',
    'struct Index {',
    '  @State count: number = 0;',
    '',
    '  build() {',
    '    Column({ space: 12 }) {',
    '    }',
    '  }',
    '',
    '  submit() {',
    '    this.log(this.count);',
    '  }',
    '}',
    '',
  ].join('\n');

  const js = [
    '// Generated by ArkMP, do not edit',
    "const { createPage } = require('@arkmp/runtime');",
    '',
    'createPage({',
    '  methods: {',
    '    submit() {',
    '      this.log(this.count);',
    '    },',
    '  },',
    '});',
    '',
  ].join('\n');

  it('生成合法 v3 map：字段齐全、sources 指回 .ets、sourcesContent 内嵌源码', () => {
    const files = byPath(
      emit({ wxml: '', wxss: '', js, json: {} }, { fileName: 'index.ets', sourcemap: true, source }),
    );
    expect([...files.keys()]).toEqual(['index.wxml', 'index.wxss', 'index.js', 'index.js.map', 'index.json']);
    const map = JSON.parse(files.get('index.js.map') ?? '') as Record<string, unknown>;
    expect(map.version).toBe(3);
    expect(map.file).toBe('index.js');
    expect(map.sources).toEqual(['index.ets']);
    expect(map.sourcesContent).toEqual([source]);
    expect(map.names).toEqual([]);
    expect(typeof map.mappings).toBe('string');
    // js 末尾追加 sourceMappingURL 注释
    expect(files.get('index.js')).toMatch(/\n\/\/# sourceMappingURL=index\.js\.map\n$/);
  });

  it('行映射可回溯：方法体内的行映射到源码对应行', () => {
    const files = byPath(
      emit({ wxml: '', wxss: '', js, json: {} }, { fileName: 'index.ets', sourcemap: true, source }),
    );
    const map = JSON.parse(files.get('index.js.map') ?? '') as { mappings: string };
    const decoded = decodeMappings(map.mappings);
    // 生成 js 第 7 行（0 起始 6）`      this.log(this.count);` → 源码第 12 行（0 起始 11）
    const line6 = decoded[6];
    expect(line6).toHaveLength(1);
    expect(line6[0][1]).toBe(0); // sources 下标
    expect(line6[0][2]).toBe(11); // 源码 0 起始行号
    // 结构行（createPage 包装）无映射
    expect(decoded[3]).toHaveLength(0);
    expect(decoded[0]).toHaveLength(0);
  });

  it('sourcemap: true 但无 source 时 map 仍合法（mappings 为空）', () => {
    const files = byPath(emit({ wxml: '', wxss: '', js, json: {} }, { sourcemap: true }));
    const map = JSON.parse(files.get('index.js.map') ?? '') as Record<string, unknown>;
    expect(map.version).toBe(3);
    expect(map.mappings).toBe('');
    expect(map.sourcesContent).toEqual([null]);
  });

  it('sourcemap 缺省不生成 map 文件', () => {
    const files = byPath(emit({ wxml: '', wxss: '', js, json: {} }));
    expect(files.has('index.js.map')).toBe(false);
    expect(files.get('index.js')).not.toContain('sourceMappingURL');
  });
});
